### ISSUE TITLE
User Defined Variables: Darcula theme doesn't allow copy/paste to another element

### ISSUE THREAD

**Issue by asfimport** [apache/jmeter#5005]
**Shane** ([Bug 63154](https://bz.apache.org/bugzilla//show_bug.cgi?id=63154&redirect=false)):
In regular theme we have config element User Defined Variables and a list of about 20 variables. If you select all the variables, edit &gt; copy, go to Test Plan and click Add from Clipboard, it pastes everything just fine.

If you do these same steps on Darcula, it does not copy the variables from the config element. BUT, if you copy anything on the computer (outside of JMeter) and click Add from Clipboard in the Test Plan, it will add that instead. Otherwise it will paste nothing.

Severity: normal
OS: All

**Comment by vlsi** [comment]
Can't reproduce in JMeter 5.6
