### ISSUE TITLE
Gradle module metadata refers to invalid 'bom' artifact

### ISSUE THREAD

**Issue by asfimport** [apache/jmeter#5322]
**Neil Farrington** ([Bug 64465](https://bz.apache.org/bugzilla//show_bug.cgi?id=64465&redirect=false)):
JMeter version 5.2.1 and beyond includes an invalid artifact 'org.apache.jmeter:bom' in the Gradle metadata file, which can cause Gradle to fail with the following error when a dependency on JMeter is present:

Could not find org.apache.jmeter:bom:5.2.1.

Gradle 6.0 publishes Gradle module metadata by default (https://blog.gradle.org/gradle-metadata-1.0). Since the JMeter project was upgraded to Gradle 6 (https://github.com/apache/jmeter/commit/6ef7d17fc345117dc61fcaa8603a3c71efd6fed3), Gradle module metadata has been published in addition to the Maven POM, which can be seen at https://repo1.maven.org/maven2/org/apache/jmeter/ApacheJMeter_core/5.2.1/

The Gradle metadata publishing should be fixed such that it doesn't include the invalid 'bom' artifact.

Severity: normal
OS: All

**Comment by izogfif** [comment]
For those using Kotlin DSL for Gradle scripts: write this in your `build.gradle.kts` file:

    implementation("org.apache.jmeter:ApacheJMeter_http:5.5") {
        exclude( "org.apache.jmeter", "bom")
    }

**Comment by vlsi** [comment]
I thought we've disabled metadata publishing

**Comment by vlsi** [comment]
🤦  I posted the same comment 3 years ago: https://github.com/apache/jmeter/issues/5322#issuecomment-1256806506

We should indeed publish `:bom` under a reasonable name.

**Comment by vlsi** [comment]
The fix is will be released in 5.6
