### ISSUE TITLE
Binary download link is broken

### ISSUE THREAD

**Issue by asfimport** [apache/jmeter#5671]
**Avnish Tomar** ([Bug 66072](https://bz.apache.org/bugzilla//show_bug.cgi?id=66072&redirect=false)):
`incorrect download link, 404 not found
https://jmeter.apache.org/[preferred]/jmeter/binaries/apache-jmeter-5.4.3.zip

Severity: normal
OS: Mac OS X 10.1

**Comment by FSchumacher** [comment]
This happens, when you access https://jmeter.apache.org/download_jmeter instead of the correct URL https://jmeter.apache.org/download_jmeter.cgi

It seems, that bing has an old link as the first search result for jmeter and download. I will try to introduce a redirect with an .htaccess rule.

**Comment by FSchumacher** [comment]
Nice, the commit message with a "try to fix" was interpreted, as if it had been fixed :) Wasn't the case six days ago, but is now.
