### ISSUE TITLE
remove xalan dependency due to it being end of life

### ISSUE THREAD

**Issue by asfimport** [apache/jmeter#5690]
**PJ Fanning** ([Bug 66171](https://bz.apache.org/bugzilla//show_bug.cgi?id=66171&redirect=false)):
Xalan is no longer supported.

https://lists.apache.org/thread/s8kjny5270ssfcp46v0fl39lk98987w7

It is better to use JAXP TransformerFactory than using xalan directly. If you add xalan dependency just to ensure that you have a JAXP compliant transformer on the classpath, this is unnecessary - the Java runtime has a built-in implementation.

Xalan dependency in:
https://mvnrepository.com/artifact/org.apache.jmeter/ApacheJMeter_core/5.5

Severity: normal
OS: All

**Comment by ahuertas-ms** [comment]
Hi team, any update/progress on this?

**Comment by vlsi** [comment]
There's a new Xalan release pending, so I guess we'll update xalan in JMeter soon: https://lists.apache.org/thread/1pmwtqy1wf6wh96h9d1cdwn8qsdy42zh

**Comment by firatkucuk** [comment]
https://github.com/HtmlUnit/htmlunit-xpath
Can this be an alternative?

I checked the same problem with htmlunit and saw this ticket:
https://github.com/HtmlUnit/htmlunit/issues/493

**Comment by vlsi** [comment]
I updated Xalan to 2.7.3 in https://github.com/apache/jmeter/pull/5880
