### ISSUE TITLE
Jmeter  code stopped building after removal of com.sun.activation » javax.activation >> 1.2.0

### ISSUE THREAD

**Issue by shrikant-c** [apache/jmeter#5720]
### Expected behavior

I'm using Apache Jmeter 5.5 libraries to generate .jmx file & integrated with IDE.

Recently my company found vulnerability in com.sun.activation » javax.activation >> 1.2.0 Jar file. Enterprise support team deleted this jar file from repository. My Gradle build is failing, please suggest any alternatives ways to come over this.

https://mvnrepository.com/artifact/org.apache.jmeter/ApacheJMeter_components/5.5 com.sun.activation » javax.activation  is runtime dependency. 

Tried excluding this jar file from build , Also this jar don't have old or newer version available in maven repository make iit work.

Please suggest how to come over this issue. Is there any alternative for this issue ?

### Steps to reproduce the problem

Remove  com.sun.activation » javax.activation >> 1.2.0 Jar file from classpath

### JMeter Version

5.5

### Java Version

1.8

### OS Version

Microsoft Windows 10

**Comment by FSchumacher** [comment]
Well, don't delete jars, when you don't know how to fix it :)

You can try to replace that jar with the file jakarta.activation-api-1.2.2.jar found at https://mvnrepository.com/artifact/jakarta.activation/jakarta.activation-api/1.2.2

I will do a PR to replace that file in trunk and would be happy to hear, if replacing helped you.

**Comment by FSchumacher** [comment]
After looking at the build failures with Java 17 of #5721 it seems, we (and that would include you) need to include the jar jakarta.activation-1.2.2.jar, which can be found via https://mvnrepository.com/artifact/com.sun.activation/jakarta.activation/1.2.2

**Comment by shrikant-c** [comment]
Thank you for your email.  Issue is resolved now.  our Artifactory is
restored both  javax.activation & Jakarta.activation under
com.sun.activation group.
Code is working as expected.

Thanks,
Shrikant
