### ISSUE TITLE
SSH Command Error：Algorithm negotiation fail

### ISSUE THREAD

**Issue by haige268** [apache/jmeter#5735]
### Steps to reproduce the problem

![1](https://user-images.githubusercontent.com/35056930/202837870-ee0fe7ef-ce9b-4e9b-8e22-19d52e7322d0.jpg)

### JMeter Version

5.5

### OS Version

Windows 10

**Comment by FSchumacher** [comment]
JMeter does not contain a SSH sampler. This must be a third party plugin. Please ask the authors/community of that plugin for help.
