### ISSUE TITLE
Enable s390x for Jenkins CI

### ISSUE THREAD

**Issue by yasiribmcon** [apache/jmeter#5746]
### Use case

We recently noticed that Travis CI has been removed for Apache JMeter : https://github.com/apache/jmeter/pull/5719
Travis CI was supporting JMeter testing on **s390x** using **OpenJDK 11**.
Jenkins CI does not support s390x yet, hence we would like to request you to start running **JMeter-Ubuntu** jobs for **s390x** architecture as well.

As per https://issues.apache.org/jira/browse/INFRA-21433, we have provided apache **four** s390x nodes, hence, same nodes can be used to enable Apache JMeter Jenkins CI as well.

We have tested JMeter-Ubuntu job by using command :
`./gradlew -Djava.awt.headless=true -PCI=true check createDist`

CI Logs : [jmeter-ubuntu.log](https://github.com/apache/jmeter/files/10192237/jmeter-ubuntu.log)

### Possible solution

Run **JMeter-Ubuntu** jobs for **s390x** architecture on Jenkins CI.

### JMeter Version

5.5.1

### Java Version

OpenJDK 11.0.17

### OS Version

Linux 5.4.0-131-generic

**Comment by vlsi** [comment]
Wow, thanks for the heads-up

**Comment by vlsi** [comment]
I've configured s390x job at the ASF Jenkins: https://ci-builds.apache.org/job/JMeter/job/JMeter%20s390x/

**Comment by vlsi** [comment]
The build passes with Java 11: https://ci-builds.apache.org/job/JMeter/job/JMeter%20s390x/2/

**Comment by yasiribmcon** [comment]
Thanks a lot ! @vlsi
