### ISSUE TITLE
Unable to load multiple users using signalR with web socket in JMetre

### ISSUE THREAD

**Issue by KetkiJoshhi** [apache/jmeter#5747]
### Expected behavior

JMeter should create sessions for all user IDs which are trying to login. 

### Actual behavior

Users are able to login to application but not able to reflect those entries in logs.

### Steps to reproduce the problem

We trying to open a websocket connection a SignalR instance, by connecting a SignalR hub, and then trying to perform a login on that websocket connection. Attempted to do this for a number of users/sessions at the same time i.e. executing with 50 user sessions via Jmeter and only 2 users/sessions was used and logged in the SignalR log.

Breakdown for multiple sessions(minimum 50)
* Connect to SignalR using a websocket connection
* perform a login call on that websocket connection to a custom endpoint on the hub connection
* maintaim that connection for the duration of the test(s) for each session
* perform a logoff on the connection after the test have run
* disconnect the websocket connection"

### JMeter Version

5.4.3

### Java Version

1.8.0_331

**Comment by milamberspace** [comment]
Seems that you have a issue in you script. This is not a bug. Please use JMeter mailing list (https://jmeter.apache.org/mail2.html ) to have help from the community.
