### ISSUE TITLE
Chrome cannot download apache-jmeter-5.5 .zip

### ISSUE THREAD

**Issue by jia9iZhang** [apache/jmeter#5782]
### The documentation URL

https://jmeter.apache.org/download_jmeter.cgi

### Feedback

Env :
```
Chrome : 109.0.0.0
macOS : 12.1 
M1 
```
issue：When I use Chrome browser to click Download apache-jmeter-5.5 .zip on the Jmeter website, there is no response😵, in Safari it works.

**Comment by FSchumacher** [comment]
I can't reproduce this. If you can still reproduce this. Please have a look in the Web Developer Tools (can be opened by pressing F12) in the Networking tab or Console tab. You should find error messages there indicating what went wrong.
Feel free to re-open it, if you can still reproduce this (and hopefully have more information)
