### ISSUE TITLE
HTTP Sampler Not Stopping or not Receiving response until we stop

### ISSUE THREAD

**Issue by Mahes498** [apache/jmeter#5802]
### Expected behavior

In my application policy issuance transaction will take around  4 to 5 mins to get response from server. 
In JMeter that same transaction some time receiving response with in 4 to 5mins. But most of the times Its not at all receiving response from server and the http sampler still running even after 5mins and HTTP sampler will run for hours if we wont stop. not receiving response or closed until we manually stop it. 
 During this time JMeter is not hanging and  I'm running with 1 user only. Same time the application working manually with out any issues.

Please let me know any setting need to changed at JMeter side

### Actual behavior

HTTP Sampler should receive response from server even the response time is High( 4mins).

### Steps to reproduce the problem

Can Not share

### JMeter Version

5.5

### Java Version

java version "1.8.0_361" Java(TM) SE Runtime Environment (build 1.8.0_361-b09) Java HotSpot(TM) Client VM (build 25.361-b09, mixed mode)

### OS Version

Windows 10

**Comment by FSchumacher** [comment]
Have you specified a timeout on the HTTP sampler?
See [docs for HTTP sampler](https://jmeter.apache.org/usermanual/component_reference.html#HTTP_Request) and look for *Connect Timeout* and *Response Timeout*

**Comment by FSchumacher** [comment]
Closing, as no answer has been received from OP and it is most probably a missing connection timeout config value.

Feel free to re-open this, if more information is provided.
