### ISSUE TITLE
Show full URL of sites tested under Recording Controller

### ISSUE THREAD

**Issue by alexsch01** [apache/jmeter#5820]
### Use case

When recording the JMeter HTTP(S) test, I can see it shows endpoints such as "/mail/u/0/" for Gmail

Is there a way for it to show as "https://mail.google.com/mail/u/0/" instead?

### JMeter Version

5.5

### Java Version

openjdk 17 latest

### OS Version

Windows 10 21H2

**Comment by FSchumacher** [comment]
Currently there is no way, to configure this.
You would have to enhance `DefaultSamplerCreater#computeSamplerName` to enable other fields than the already allowed ones.
Might be useful, so a PR would be welcome.

**Comment by alexsch01** [comment]
@FSchumacher Wow, thank you so much for the PR.
This change works very well for my use case - I tested it with #{url} and it did exactly what I wanted it to do

Will close the issue if/when the PR is merged

**Comment by en-error1** [comment]
OK

**Comment by vlsi** [comment]
This has been resolved in https://github.com/apache/jmeter/pull/5869
