### ISSUE TITLE
Mac OSX ⌘ copy/paste (paste modifier key) inconsistent between textbox and textArea

### ISSUE THREAD

**Issue by steverawlins-zebra** [apache/jmeter#5905]
### Expected behavior

Honor the Mac's Command-key, ⌘.

#### Operating System

MacOSX Ventura 13.2.1

### Actual behavior

Does not respond to the standard paste buffer on Mac.  ⌘ does not operate the copy/paste within JMeter text boxes (but it seems to within textAreas, such as the body of an HTTP Request!)

### Steps to reproduce the problem

within the JMeter gui, on the Mac, click on a element such as "User Defined Variables".

Select some text anywhere, such as within the Description column.

Copy using ⌘-C

Now select a different app, such as any text editor.

Paste using ⌘-V

Nothing happens.  The text should appear.

Same problem going the other way.

You have to switchover to the control key when on a textBox in JMeter, using ctl-C  (^C) and ctl-V (^V) when within JMeter GUI, but ⌘ when outside.   Except for textArea. Inside a textArea, the native ⌘ seems to work OK.

### JMeter Version

5.5

### Java Version

17

### OS Version

MacOS

**Comment by vlsi** [comment]
Am I right you use Metal look and feel?
The keymaps are look-and-feel specific, so they might behave differently.

The issue does not reproduce with Darklaf look and feel, and it does copy&paste with ⌘ key for me.
Does Darklaf resolve the issue for you?

**Comment by steverawlins-zebra** [comment]
Yes (to both).  Yes, I was using Metal.  Yes, Darklaf seems to resolve the issue.   Thank you.
