### ISSUE TITLE
java.net.BindException: Can't assign requested address (Bind failed)

### ISSUE THREAD

**Issue by zhengtulymGh** [apache/jmeter#5933]
### Actual behavior

![image](https://github.com/apache/jmeter/assets/13768025/5884c325-61d3-4696-8b9c-2b77211fa506)

### Steps to reproduce the problem

I configured an HTTP domain name that can be accessed, but when I started it, the request result reported an error. Why is this happening?
![image](https://github.com/apache/jmeter/assets/13768025/48245c90-bbb2-4c61-9d7d-aff569538347)

I accessed this HTTP interface address in the browser, although it returned a 404 error, I can see that the domain is accessible.
![image](https://github.com/apache/jmeter/assets/13768025/8ca0e36b-5f70-4908-ab04-22217159306c)

### JMeter Version

5.5

### Java Version

java version "1.8.0_371"
Java(TM) SE Runtime Environment (build 1.8.0_371-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.371-b11, mixed mode)

### OS Version

macOS Monterey 12.6.1

**Comment by zhengtulymGh** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，来件已收到，我会尽快回复您。。。。

**Comment by zhengtulymGh** [comment]
Hi @vlsi , the address "webgpt-spider-backend.vmic.xyz" is a domain name for a remote service, not a local address. 
And this is my advanced configuration.
![image](https://github.com/apache/jmeter/assets/13768025/99076575-4af1-45cd-818b-90c69fc0704f)

**Comment by vlsi** [comment]
`source address` configures IP address that should be used for sending a request. It is useful when the load generator has several network interfaces or at least several IP addresses.
I suggest to clear `Source address` field.
