### ISSUE TITLE
JMeter plugins don't work in next JMeter release (5.5.1-SnapShot ebc1615)

### ISSUE THREAD

**Issue by ra0077** [apache/jmeter#5942]
### Expected behavior

After of the JMeter plugins jar installed, an icon appear in JMeter menu

Here a screenshot with 5.5.1-SnapShot f64dec5
![JMeter_5 5 1-SnapShot f64dec5_working](https://github.com/apache/jmeter/assets/16882234/46636d57-5767-47a7-ae1c-e2eab513a3e5)

### Actual behavior

No JMeter Plugins icon
[jmeter.log](https://github.com/apache/jmeter/files/11547438/jmeter.log)
![JMeter_5 5 1-SnapShot ebc1615_not_working](https://github.com/apache/jmeter/assets/16882234/b7a2e006-eadf-4549-b1e2-c86ae63afd60)

### Steps to reproduce the problem

Install JMeter plugins
Execute JMeter.bat

### JMeter Version

5.5.1-SnapShot ebc1615

### Java Version

openjdk version "17" 2021-09-14

### OS Version

Microsoft Windows 11

**Comment by vlsi** [comment]
Fixed in 29abbcf883da94dd065191ef828faa65028689bf
