### ISSUE TITLE
中文乱码，chinese is show error!

### ISSUE THREAD

**Issue by mouday** [apache/jmeter#5945]
### Steps to reproduce the problem

中文乱码

<img width="1152" alt="image" src="https://github.com/apache/jmeter/assets/24365682/e1d39992-d288-468a-beb7-bf77f4c79eb8">

### JMeter Version

5.5

### Java Version

java version "1.8.0_361" build 1.8.0_361-b09

### OS Version

Mac OS X 10.14.4 18E2035

**Comment by vlsi** [comment]
Can you try changing look and feel?

**Comment by mouday** [comment]
I try change style, it is ok.

<img width="1440" alt="image" src="https://github.com/apache/jmeter/assets/24365682/8fd83efe-ec26-4aa1-bcb2-8abbac52f357">

**Comment by mouday** [comment]
> Can you try changing look and feel?

thank you!

**Comment by vlsi** [comment]
Could you please tells us which styles work and which do not?

**Comment by mouday** [comment]
dark style is error, system style is ok.
![image](https://github.com/apache/jmeter/assets/24365682/dfae855f-18d9-4386-bc35-2897ccd5972c)
