### ISSUE TITLE
Consider UTF-8 as the default HTTP encoding

### ISSUE THREAD

**Issue by vlsi** [apache/jmeter#6005]
### Use case

Sending unicode data should not corrupt it.

### Possible solution

We might consider using UTF-8 by default instead of the current ISO_8859_1.

See https://github.com/apache/jmeter/blob/13793b74d96576731062e83b3c365b2adbe6a8df/src/protocol/http/src/main/java/org/apache/jmeter/protocol/http/sampler/PostWriter.java#L52

See
* https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#selecting-a-form-submission-encoding (If candidate encodings is empty, return [UTF-8](https://encoding.spec.whatwg.org/#utf-8)

### JMeter Version

5.5

**Comment by koudela5** [comment]
I wonder if following lines (the information about the default encoding) in jmeter.properties are still valid based on this change:
# The encoding to be used if none is provided (default ISO-8859-1)
#sampleresult.default.encoding=ISO-8859-1

**Comment by vlsi** [comment]
Good catch. I somehow missed that `org.apache.jmeter.samplers.SampleResult#DEFAULT_HTTP_ENCODING` was used as a fallback for `org.apache.jmeter.samplers.SampleResult#DEFAULT_ENCODING`.
