### ISSUE TITLE
JMeter 5.6 - ThreadGroups are running endlessly in non-gui mode

### ISSUE THREAD

**Issue by dgetzlaf** [apache/jmeter#6008]
### Expected behavior

In gui mode, JMeter acts as always.
In *non-gui mode* JMeter runs all Thread Groups endlessly, when there is no specified Thread lifetime.

JMeter was used to run the number of configured Loops - even without a specified Thread lifetime.

![image](https://github.com/apache/jmeter/assets/54536760/45ad99ff-569d-43d2-aed8-4e5c57bec6de)

Also there was a Property in the JMX beneath the ThreadGroup
```
<elementProp name="ThreadGroup.main_controller" elementType="LoopController" guiclass="LoopControlPanel" testclass="LoopController" testname="Loop Controller">
    <boolProp name="LoopController.continue_forever">false</boolProp>
    <stringProp name="LoopController.loops">1</stringProp>
</elementProp>
```

### Actual behavior

Since JMeter 5.6 the ThreadGroups without a specified Thread lifetime run endlessly.
Also the property in the JMX beneath the ThreadGroup *is missing*
```
    <boolProp name="LoopController.continue_forever">false</boolProp>
```

### Steps to reproduce the problem

Open a TestPlan from JMeter 5.5 with JMeter 5.6, save it and review the difference.

Otherwise use this test plan [non-stopping-threads-jmeter-5.6.jmx.txt](https://github.com/apache/jmeter/files/11868850/non-stopping-threads-jmeter-5.6.jmx.txt)

run in *gui mode* -> should execute...
.. the setUp Thread Group once
..the Thread Group 4 times

- run in *non-gui mode* `<path-to-jmeter-5.6>\jmeter.bat -t non-stopping-threads-jmeter-5.6.jmx -l jmeter.log -n`
- tail the jmeter.log 
- see that the setUp Thread Group is not stopping (consecutive printing of 'Should exist only once')
- abort the test execution

### JMeter Version

5.6

### Java Version

openjdk version "17.0.7" 2023-04-18 LTS OpenJDK Runtime Environment (build 17.0.7+7-LTS) OpenJDK 64-Bit Server VM (build 17.0.7+7-LTS, mixed mode, sharing)

### OS Version

Microsoft Windows [Version 10.0.19045.3086]

**Comment by vlsi** [comment]
> Since JMeter 5.6 the ThreadGroups without a specified Thread lifetime run endlessly.
>Also the property in the JMX beneath the ThreadGroup is missing

The default value is indeed not saved.
However, it should be loaded as "default".

**Comment by sginsbourg** [comment]
Should consider a hotfix such as a quick 5.6.1 version release.


Thank you
SG


________________________________

**Comment by mauritz-lovgren** [comment]
Is there a workaround to this issue before 5.6.1 comes out? Such as setting a value to the LoopController attribute to make it stop after executing the tests just like it does in UI mode?

**Comment by vlsi** [comment]
The workaround is to edit `.jmx` manually so you add `<boolProp name="LoopController.continue_forever">false</boolProp>` under `<elementProp name="ThreadGroup.main_controller"`.

Unfortunately, it will disappear every time you save the file in JMeter 5.6.

An alternative option is to use a different thread group. For instance, Open Model Thread Group.

**Comment by mauritz-lovgren** [comment]
> The workaround is to edit `.jmx` manually so you add `<boolProp name="LoopController.continue_forever">false</boolProp>` under `<elementProp name="ThreadGroup.main_controller"`.
> 
> Unfortunately, it will disappear every time you save the file in JMeter 5.6.
> 
> An alternative option is to use a different thread group. For instance, Open Model Thread Group.

Thank you, that will do the trick for us. We store the jmx file in GitHub, so we can add this manually to make the automated tests (that run in non-UI mode) work again until 5.6.1 is out! Thanks!

**Comment by vlsi** [comment]
5.6.1 is released, enjoy

**Comment by Sreenitti** [comment]
I am using the latest version 5.6.3 and I am still facing this issue even though ```<boolProp name="LoopController.continue_forever">false</boolProp>``` is automatically added under ```<elementProp name="ThreadGroup.main_controller".```
