### ISSUE TITLE
HTTP Request sampler displays default values in some fields

### ISSUE THREAD

**Issue by koudela5** [apache/jmeter#6026]
### Expected behavior

Protocol and Content encoding fields in HTTP Request sampler should display empty value in GUI by default.
![image](https://github.com/apache/jmeter/assets/113984709/4f2a73d6-4a24-4cef-b35c-8e4d3450347f)

### Actual behavior

When you add or display HTTP Request sampler then Protocol and Content encoding fields display a default value. Removing the values and saving the test plan causes displaying the default values again.

### Steps to reproduce the problem

Add a new HTTP Request sampler to a test plan and check Protocol and Content encoding fields or open a test plan created in a previous version of JMeter where HTTP Request sampler had Protocol and Content encoding fields empty.

### JMeter Version

5.6.1

**Comment by vlsi** [comment]
Does it really bother you?
What problems does it bring?

By the way, the default value is not saved, so JMX is not getting larger, and default values do not exist in memory, so Java heap usage is not increased.

---

I saw that behavior, and after a bit of thought I concluded it is fine, and it makes it easier for the users to see what is the actual encoding.

**Comment by koudela5** [comment]
It is very confusing especially along with HTTP Request Defaults, see following:
![image](https://github.com/apache/jmeter/assets/113984709/7bd35442-01c5-4acd-b0e1-733e02c7053f)
You see that HTTP Request overrides values in the HTTP Request Defaults but actually the HTTP Request executes with the values set in the HTTP Request Defaults because the HTTP Request displays just the default values. Basically you can't distinguish between default and overridden values.

BTW the same behaviour have HTTP Request Defaults config element but it is acceptable.

**Comment by vlsi** [comment]
Just wondering what would you say about checkboxes?

For instance, open "HTTP Request Defaults", switch to "Advanced" tab, and try to guess if `[ ] Save response as MD5 hash?` would override the corresponding setting in HTTP request defaults or not.

What would you expect if you have `[x] Save response as MD5 hash?` for HTTP Request, and the same checkbox is unchecked for HTTP Request Defaults?

**Comment by koudela5** [comment]
That's good question. You cannot distinguish between false and default state. I would leave the bevaviour as it was in version 5.5 and below for now. What about using a tri-state checkbox in a future version of JMeter (or completely get rid of checkboxes for such cases)? With states true, false, default/inherit.
