### ISSUE TITLE
Jmeter 5.6 shows 0 as a min response time in summary report

### ISSUE THREAD

**Issue by rupaliwar** [apache/jmeter#6043]
### Expected behavior

Minimum response time should get display under min column in JMeter summary report

### Actual behavior

Minimum response time column shows '0' for all transaction/requests under min column in JMeter summary report

### Steps to reproduce the problem

![Summaryreport](https://github.com/apache/jmeter/assets/54849796/9e06e429-adf6-4c2f-91b1-be957934a6f1)

### JMeter Version

5.6

### Java Version

1.8

### OS Version

Win 10 pro

**Comment by gadaborshev** [comment]
The same problem, version 5.6.2 macOS Ventura
<img width="1230" alt="Monosnap Thread Group wiki jmx (:Users:ruslangadaborsh:Thread Group wiki jmx) - Apache JMeter (5 6 2) 2023-07-25 11-02-36" src="https://github.com/apache/jmeter/assets/103312341/352a9481-cb5b-40e9-9f18-f3e5e92b552e">

**Comment by praveenperf99** [comment]
This is not fixed even in 5.6.3. Still the minimum response times are zero for all the samples and controllers in summary report.
