### ISSUE TITLE
Non HTTP response code: org.apache.htthttps://jmeter.apache.org/usermanual/component_reference.htmlp.conn.HttpHostConnectException

### ISSUE THREAD

**Issue by rizwanraj** [apache/jmeter#6049]
### Expected behavior

Hello JMeter Team,

I was performing Load testing on my project using JMeter. 
I did a recording of our web application via Blazemeter and then converted the same into .jmx file and then opened it with Jmeter v5.5 and v5.6 and when I am running it, I am getting the below error as below

Response message: Non HTTP response message: Connect to application failed: Connection refused: connect
Response message:Non HTTP response message: Connect to {projectURL}:443 [{projectURL}/64:ff9b:0:0:0:0:d40:6099] failed: Connection refused: connect

### Steps to reproduce the problem

I am just running the JMX file and it is not working. The first request itself is failing.

### JMeter Version

5.5 and 5.6

### Java Version

17

### OS Version

Windows 10 Pro(19045.3208)

**Comment by rizwanraj** [comment]
I am attached the screenshot, due to security reason I won't be able to provide the project details. So, I recorded a script for Google search via BlazeMeter and converted the same into .jmx file. I ran the .jmx file using JMeter and it also did not work.
Please check and let me know if you need any help. 
![JMeter error](https://github.com/apache/jmeter/assets/71756450/4646a1a0-e5b0-4c84-b523-08e918c93df0)

**Comment by santhosh-vikraman** [comment]
Are you using a proxy for normal web connection?

**Comment by rizwanraj** [comment]
> Are you using a proxy for normal web connection?

Hi Santosh,

thank you replying, I am not using proxy connection. It is my regular normal web connection. I tried to change my IP address but still it does not work.

**Comment by mawasak** [comment]
Hi,
1. Are you sure that your corpo-net is not using proxy?
2. Can you try to create simple JMeter script not using Blazemeter and run it?
3. The exception comes from the HttpClient low-level library, not from JMeter directly
4. You can turn on LogViewer and change LogLevel to DEBUG to see more messages from HttpClient
![obraz](https://github.com/apache/jmeter/assets/1379060/4f67d704-4c1d-4546-841d-255d9b140b70)

![obraz](https://github.com/apache/jmeter/assets/1379060/2f39cc7d-280a-45e1-a46b-b522aa39e1b1)

**Comment by mawasak** [comment]
You can also check how JMeter/HttpClient behaves when run with -Djava.net.preferIPv4Stack=true

**Comment by rizwanraj** [comment]
Hello Mawasak,

I tried with the above steps mentioned and still see failure. I am attaching the images and Log file for further reference.

![image](https://github.com/apache/jmeter/assets/71756450/c3638cfe-c344-4c59-9bfc-fc75d6a337c6)
![image](https://github.com/apache/jmeter/assets/71756450/1a840d41-1f37-4483-a1e5-127fed3f2bc6)


[Log.txt](https://github.com/apache/jmeter/files/12093894/Log.txt)

**Comment by mawasak** [comment]
I look like network issue:-/ 
Can you successfully run any request? To a different endpoint than google/

**Comment by rizwanraj** [comment]
No, I am able to run any request.

**Comment by rizwanraj** [comment]
> I look like network issue:-/ Can you successfully run any request? To a different endpoint than google/

No, I am not able to run any request.
Also, the network settings are fine.
