### ISSUE TITLE
Jmeter 5.6.2 shows 0 as a min response time in summary report

### ISSUE THREAD

**Issue by gadaborshev** [apache/jmeter#6055]
### Expected behavior

Minimum response time should get display under min column in JMeter summary report

### Actual behavior

Minimum response time column shows '0' for all transaction/requests under min column in JMeter summary report

### Steps to reproduce the problem

<img width="1230" alt="Monosnap Thread Group wiki jmx (:Users:ruslangadaborsh:Thread Group wiki jmx) - Apache JMeter (5 6 2) 2023-07-25 11-02-36" src="https://github.com/apache/jmeter/assets/103312341/5401fec8-35d2-4630-8c3e-9572e19131c0">

### JMeter Version

5.6.2

### Java Version

20.0.2 2023-07-18

### OS Version

macOS Ventura 13.4.1

**Comment by vlsi** [comment]
Duplicates https://github.com/apache/jmeter/issues/6043
