### ISSUE TITLE
Downloading of embedded resources via HTTP Request Default not working on v5.6.2

### ISSUE THREAD

**Issue by owenpahl** [apache/jmeter#6076]
### Expected behavior

When setting embedded resources to be downloaded via the HTTP Request Defaults, I expect all samplers in scope to inherit this config and download any found resources. In v5.6.2 this is no longer working.

I've tested thing against both Java 1.8 (OpenJDK Runtime Environment (Temurin)(build 1.8.0_382-b05)) and Java 17 (OpenJDK Runtime Environment (build 17+35-2724)). This works as expected in v5.5

### Actual behavior

JMeter follows any redirects but fails to download any embedded resources if this is set via the HTTP Request Defaults. If it is set directly on a sampler it will download the resources.

### Steps to reproduce the problem

Run the attached script. It contains two samplers (in different transaction controllers) with the same request (http://google.com), one with embedded resources enabled directly and the other with embedded resources enable via HTTP Request Defaults.

Run this with JMeter v5.5 both transaction controllers show 4 requests (1 GET, 1 Redirect, and 2 .png images)
Run this with JMeter v5.6.2, the sampler where embedded resources are enabled directly shows the same as under v5.5. The other sampler where the embedded resources are enabled via HTTP Request Defaults only shows 2 requests (1 GET, 1 Redirect).

[parallel download test.zip](https://github.com/apache/jmeter/files/12593174/parallel.download.test.zip)

### JMeter Version

5.6.2

### Java Version

OpenJDK Runtime Environment (build 17+35-2724

### OS Version

Microsoft Windows [Version 10.0.19045.3324]

**Comment by owenpahl** [comment]
I've started digging into how this side of JMeter works. From what I can grasp the issue appears to be caused by two things:

1. The `HTTPSampler.image_parser` property is now retained when it is false (unselected), previously (v5.5) it was removed from the property map completely. This is possibly a side-effect of the move to the kotlin based schema model.

2. If a property is already defined, its value is not replaced by that in the config item property. Which I think in most cases would be correct (eg,  if the domain is defined on a sampler this is take precedence over that in the config defaults), however for the boolean properties that map to checkboxes this means the default will never be applied as the property exists (with a value of false).

Any thoughts on the correct way to address this? 
Do we change the behaviour back to removing false boolean properties? Or maybe define how values are replaced when there are defaults in scope better? 

I sure don't want to have to go back though all our existing scripts and enable downloading embedded resources on each sampler ...

**Comment by vlsi** [comment]
> I sure don't want to have to go back though all our existing scripts and enable downloading embedded resources on each sampler

Sure that is not the way to deal with it

**Comment by vlsi** [comment]
This is relevant: https://github.com/apache/jmeter/issues/6026#issuecomment-1614520251

**Comment by vlsi** [comment]
In other words, imagine the following:

1) You check `[x] retrieve embedded resources` in both `HTTP Request` and `HTTP Request Defaults`
2) Then you decide you do not need resources in `HTTP Request`, so you uncheck resource retrieval there

How should JMeter behave? Should it treat "unchecked resource retrieval at HTTP Request" a priority or should it always assume that "unchecked values are void, so defaults should be used instead"?

At the same time, there might be a different case: what if the user wants to **globally** disable resource retrieval? How "unchecked" resource retrieval checkbox would override "checked" ones at HTTP Request level?

---

At best, we should make UI explicit when it comes to `value not specified, using default` vs `value is specified`.

For checkboxes it might require two new rendering states in addition to "true" and "false": "using default (true)" and "using default (false)"

**Comment by vlsi** [comment]
@owenpahl , it looks like https://github.com/apache/jmeter/pull/6199 fixes this issue. Do you think you could test https://github.com/apache/jmeter/pull/6199 ?

**Comment by QAInsights** [comment]
@vlsi I tested #6199 , it works fine.

**Comment by vlsi** [comment]
F
