### ISSUE TITLE
The counter function calculation error in HTTP Request.

### ISSUE THREAD

**Issue by xmlbw** [apache/jmeter#6077]
### Expected behavior

Increment by 1 each time

### Actual behavior

Increment by 2 each time

### Steps to reproduce the problem

![image](https://github.com/apache/jmeter/assets/16716813/1d1375f8-2fc8-4586-9839-e43e794ce60e)

### JMeter Version

5.6.2

### Java Version

1.8.0_371

### OS Version

10.0.19045.3324

**Comment by Ninja-Cyborg** [comment]
I've found the same issues, it occurred in version 5.6.2 but not in 5.5
# Possible cause:
The following changes were made in jmeter.properties file, as it says it will be removed in future. For now, uncommenting line 1063 and setting it true works just as fine as in JMeter 5.5
![image](https://github.com/apache/jmeter/assets/66517017/350b3bdb-75d8-42ec-8caa-b822de0a0074)
* jmeter.properties file is located under bin directory
# The Counter config element works fine in both versions. If it fits your use case, you can try it:
![image](https://github.com/apache/jmeter/assets/66517017/7d291c0e-1a31-47be-8ae8-d3997995c30b)
* Make sure to use at right scope

**Comment by xmlbw** [comment]
According to the above method, it works normally.
