### ISSUE TITLE
ConstantThroughputTimer can't use __P property input

### ISSUE THREAD

**Issue by bcdevlucas** [apache/jmeter#6086]
### Expected behavior

No errors.

### Actual behavior

Error.

An error occurred: Error in NonGUIDriver Problem loading XML from:'/Users/lucas/Omise/omise_authn-jmeter/tests/login-and-get-token.jmx'. 

Cause:
NumberFormatException: For input string: "${__P(TARGET_THROUGHPUT,60.0)}"

Detail:com.thoughtworks.xstream.converters.ConversionException: 
cause-exception     : com.thoughtworks.xstream.converters.ConversionException
cause-message       : 
first-jmeter-class  : org.apache.jmeter.save.converters.TestElementConverter.unmarshal(TestElementConverter.java:109)
class               : org.apache.jmeter.save.ScriptWrapper
required-type       : org.apache.jmeter.save.ScriptWrapper
converter-type      : org.apache.jmeter.save.ScriptWrapperConverter
path                : /jmeterTestPlan/hashTree/hashTree/hashTree[2]/ConstantThroughputTimer/doubleProp/value
line number         : 691
version             : 5.5

### Steps to reproduce the problem

`
<ConstantThroughputTimer guiclass="TestBeanGUI" testclass="ConstantThroughputTimer" testname="Constant Throughput Timer" enabled="true">
    <doubleProp>
      <name>throughput</name>
      <value>${__P(TARGET_THROUGHPUT,60.0)}</value> <-- this DOESN'T WORK!!!!!
      <savedValue>0.0</savedValue>
    </doubleProp>
    <intProp name="calcMode">2</intProp>
  </ConstantThroughputTimer>
`

### JMeter Version

5.5

**Comment by FSchumacher** [comment]
How did you end up with that XML fragment? Did you edit the XML by hand?
If I save a constant throughput timer that I edited in the GUI, I get a `stringProp` instead of a `doubleProp`.
