### ISSUE TITLE
GRPC service streaming on Jmeter

### ISSUE THREAD

**Issue by nptri** [apache/jmeter#6087]
### Use case

Since more and more GRPC microservices coming, we need a decent way to test the capabilities of GRPC API, a good/invested GRPC calling would be amazing and pushing us to get the job done.
The behavior should at least contains:
- A streaming ability (which the current ONLY GRPC plugin from ZaloOS can't do it)
- Ways to interact with the data in return.

Thank you for considering

### JMeter Version

5.6.2

### Java Version

JDK 17.0.8

**Comment by pmirek** [comment]
Any timeline for possible implementation? Having GRPC supported in core JMeter distribution would be great, thanks!

**Comment by flinux-sudo** [comment]
Any new updates on this? it really would be great to have it, thanks

**Comment by michal3141** [comment]
Sounds like a great idea. Any updates on this would be appreciated.

**Comment by lpankaz** [comment]
Hey, that would be a real deal-breaker! When can we expect that?

**Comment by kacper51011** [comment]
Perfect idea, Im waiting for it!

**Comment by ash-man** [comment]
Hey, we are also looking at this ! Any updates ?

**Comment by nptri** [comment]
Currently gRPC maybe not their prioritize, so it's best to move to Gatling / phiSgr's gRpc library.

**Comment by flinux-sudo** [comment]
> Currently gRPC maybe not their prioritize, so it's best to move to Gatling / phiSgr's gRpc library.

thank you :D, it is not ideal solution to move to Gatling, too many tests were created in jmeter to do that. Hopefully it will be prioritized more when more and more grpc microservicess are coming like you mentioned in the issue.

**Comment by nptri** [comment]
request for comment on this feature.
Gently tag @vlsi to see if gRPC is possible.

**Comment by pmirek** [comment]
Thanks for taking this under your consideration

**Comment by nptri** [comment]
in case someone stumbles this request.
.
You can consider alternatives such as k6 Grafana, Gatling Enterprise, Fiddler.
Coding for the APIs of these tool are verbose enough to understand.
Else, you can wait, until when then no one knows.
