### ISSUE TITLE
在Jmeter中HTTP取样器发送大文件响应时间过长的问题

### ISSUE THREAD

**Issue by SuperMeng1209** [apache/jmeter#6091]
### Expected behavior

您好，由于公司方要求使用jmeter3.3版本。我们在使用jmeter3.3的http取样器发送50Mb文件的时候，发现他的响应时间达到16s。后使用了postman进行发送请求，仅使用了300ms。然后我再次使用jmeter3.3发送50Mb文件后，观察后端实际上过了很久才接到相应的请求。最后我更换了10Kb的文件进行发送，发现jmeter3.3的响应时间变得很快。不知道是不是因为jmeter3.3中将文件的处理也计算在了响应时间当中。

### Actual behavior

由于在局域网内使用，没有相应的截图

### Steps to reproduce the problem

1、公司方要求使用jmeter3.3版本。
2、我们在使用jmeter3.3的http取样器发送50Mb文件的时候，发现他的响应时间达到16s
3、后使用了postman进行发送请求，仅使用了300ms
4、然后我再次使用jmeter3.3发送50Mb文件后，观察后端实际上过了很久才接到相应的请求
5、最后我更换了10Kb的文件进行发送，发现jmeter3.3的响应时间变得很快
不知道是不是因为jmeter3.3中将文件的处理也计算在了响应时间当中。

### JMeter Version

jmeter3.3

### Java Version

jdk8

### OS Version

window7

**Comment by SuperMeng1209** [comment]
> Google 将描述翻译为：
> 
> > 您好，因为公司要求使用jmeter3.3版本。当我们使用jmeter3.3的http采样器发送50Mb的文件时，我们发现它的响应时间达到了16s。最后使用postman发送请求，只用了300ms。然后我再次使用jmeter3.3发送50Mb的文件，观察到后端实际上花了很长时间才收到相应的请求。最后我改了10Kb的文件发送，发现jmeter3.3的响应时间变得很快。不知道是不是因为jmeter3.3在响应时间里也包含了文件处理。
> 
> JMeter 3.3 确实很老了。尝试在当前版本的 JMeter 上重现该行为。是的，通常响应时间是在响应的最后一个字节到达 JMeter 时计算的。

谢谢，因为我们近期可能无法更换版本。我想确认一下，老版本3.3中，是不是把加载文件内容也计算到响应时间内了？ 我想以这个推动公司更换新版本的jmeter。

**Comment by FSchumacher** [comment]
Again, google translated the answer to:

> Thank you, because we may not be able to change the version in the near future. I would like to confirm, in the old version 3.3, does the content of the loaded file also count into the response time? I want to use this to push the company to replace the new version of jmeter.

As far as I know, nothing has changed in that respect in the last versions. But you can always try for yourself by using the [non-test element HTTP mirror server](https://jmeter.apache.org/usermanual/component_reference.html#HTTP_Mirror_Server). You can send requests to that mirror server with a  special HTTP header `X-Sleep` to control the duration of the server response.

**Comment by SuperMeng1209** [comment]
> 再次，谷歌将答案翻译为：
> 
> > 谢谢您，因为我们近期可能无法更改版本。我想确认一下，在旧版本3.3中，加载文件的内容是否也计入响应时间？我想借此推动公司更换新版本的jmeter。
> 
> 据我所知，最新版本在这方面没有任何改变。[但您始终可以使用非测试元素 HTTP 镜像服务器](https://jmeter.apache.org/usermanual/component_reference.html#HTTP_Mirror_Server)自行尝试。您可以使用特殊的 HTTP 标头向该镜像服务器发送请求`X-Sleep`，以控制服务器响应的持续时间。

收到，谢谢。我在回去测试一下
