### ISSUE TITLE
Facing Error "Illegal character in authority at index" When Sending Parameter String Password with Bracket

### ISSUE THREAD

**Issue by MikailSonmez** [apache/jmeter#6095]
### Expected behavior

Body Data should accept bracket as String, when it is inside of the String

{"email":"${__P(username, ******)}", "password":"${__P(password, example)4444)}"}

### Actual behavior

Body Data should`nt accept bracket as String, when it is inside of the String

### Steps to reproduce the problem

1- Create HTTPS Request with Body Data
2- Write inside of body data bracket punctuation as Parameter as String
3- Run the HTTPS Request
4- Facing Error "Illegal character in authority at index"

Note: Delimiter added delimiter to the bracket, \), and that time the Property reference was processed well, but delimiter was not removed from the output value.

Note: Tried this,
{"email":"${__P(username, ******)}", "password":"${__P(password, example\)4444)}"}
and this was ok, property understood it as password, but the the delimiter was not removed.
if the password is example\)4444 we shoudl write in the property like this: example\\\)4444
- Last backslash for saving the brancket, 2 backslash to set \ character as part of the pwassord string

### JMeter Version

5.5

### Java Version

java version "11.0.18" 2023-01-17 LTS

### OS Version

10.0.19044 Builde 19044

**Comment by FSchumacher** [comment]
To boil it down a bit, you would like to change the behaviour of the `__P` function to un-escape special characters so that
`")" == "${__P(somevar,\))}"` would be true.

Have you tried to use the `__unescape` function? For example `$__P(password,${__unescape(example\)444)})}`

**Comment by Frenetikon** [comment]
Hi FSchumacher, We tried backslash escape character in `__P`, and while JMeter could understand the payload well, `__P` left backslash it in the password therefore it induced another problem. We did not know this `__unescape` function, so we haven't tried it, but we'll do it soon. Thanks for your fast reply.

**Comment by MikailSonmez** [comment]
Thanks for comments, Fixed!
