### ISSUE TITLE
CI: Add Auto-Format GitHub Actions for Java files

### ISSUE THREAD

**Issue by SaptarshiSarkar12** [apache/jmeter#6161]
### Use case

This project has a code style available in the `config/checkstyle` directory. **Checking whether the code in the Pull Requests or branches follows the project's code style and applying fixes accordingly is a tedious work**.

### Possible solution

A GitHub Action can be set up to check for checkstyle violations and automatically format those files according to the checkstyle configuration. The changes will be automatically pushed to the branch and PR's source branch.
**I would like to work on this issue.**

### JMeter Version

5.6.1

### Java Version

java 20.0.2 2023-07-18

### OS Version

Ubuntu 23.10

**Comment by vlsi** [comment]
"Checkstyle" is already configured, and I suggest we do not increase its verifications as Checkstyle produces hard to understand failure messages.

Do you think you could try integrating Openrewrite? See https://github.com/pgjdbc/pgjdbc/pull/2979

**Comment by vlsi** [comment]
We use Autostyle for some of the automatic fixes: https://github.com/autostyle/autostyle

**Comment by SaptarshiSarkar12** [comment]
@vlsi Yes, I just learned how to integrate Openrewrite in my Open-Source Java project - [Drifty](https://github.com/SaptarshiSarkar12/Drifty) and it is very good at its work. You can see that the last commit to that repo is about the Java files being formatted.
![image](https://github.com/apache/jmeter/assets/105960032/9c98ec46-7b4a-4f90-8196-df049c87d07d)
I will do two things -
- Add openrewrite to maven pom.xml file
- Add a GitHub Action to auto-format and push the changes to the respective branches and PRs.

So, can I work on this issue?

**Comment by vlsi** [comment]
I'm -0.5 for pushing formats from GitHub Actions. I am afraid it would violate the Apache Software Foundation rules.
I would rather start with making PRs fail if there are unformatted changes. WDYT?

**Comment by SaptarshiSarkar12** [comment]
@vlsi I am not sure if it would violate Apache Software Foundation Rules. But, automating the formatting of files is just saving time a bit - which I think helps developers to concentrate more on the logic and also helps in faster review.
It also gives a great experience for other contributors - they don't have to check for failure in code style themselves (let's think if there are huge changes made and multiple checkstyle violations have occurred).

**Comment by vlsi** [comment]
> I am not sure if it would violate Apache Software Foundation Rules. 

@SaptarshiSarkar12 , please show us the relevant issue at https://issues.apache.org/jira/browse/LEGAL or https://lists.apache.org/list.html?legal-discuss@apache.org that concludes that "robots are fine to commit formatting changes to the main branches".
Otherwise, I am not going to discuss and merge such an Action.

**Comment by SaptarshiSarkar12** [comment]
@vlsi Sorry, I couldn't find any relevant issue. Might be because it is a rule.
I am closing this issue then.

**Comment by SaptarshiSarkar12** [comment]
@vlsi I have one question. Does **Apache v2 license** explicitly specify any such rules?

**Comment by vlsi** [comment]
Apache 2 license does not forbid that. However, there are certain rules within the Apache Software Foundation.

You might raise an issue at LEGAL or start a discussion to get clarification. However, I doubt they would allow such bots.

**Comment by SaptarshiSarkar12** [comment]
@vlsi Okay. I understood.
No, its fine - Apache can make rules. No problem in that. I just wanted to know if apache license mentions any kind of this statement as it is used by my project :sweat_smile:.
