### ISSUE TITLE
Set minimum Java version to 11

### ISSUE THREAD

**Issue by rbourga** [apache/jmeter#6172]
### Use case

A couple of JMeter plugins are (or will be) requiring Java 11 as the new minimum version.
For example, Selenium has stopped supporting Java 8 and is now requiring Java 11 since 30 Sepetember 2023. But as JMeter is still supporting Java 8, this is preventing the updates of the JMeter Web-Driver plugin to keep in sync with Selenium releases. Web-Driver is currently using the last Selenium Java 8 libraries, i.e., version 4.13, whereas Selenium has recently released version 4.16! So we are slowly falling behind.

What are the plans to upgrade JMeter to Java 11 as minimum version instead of Java 8  so that we can benefit from Java 11 plugins without having to worry about the Java version ?

### JMeter Version

5.6.2

**Comment by vlsi** [comment]
JMeter supports running with Java 8..21, so it should be fine if some plugins require Java 11.

At the same time, the next major release JMeter 6.0 would require Java 17, see https://lists.apache.org/thread/hb6ksgxgs6q1lqcvf7q1lhxcqjdjjvk0
