### ISSUE TITLE
 use customize function, In some cases，info level is ok ，debug lever is wrong

### ISSUE THREAD

**Issue by ibingdian** [apache/jmeter#6198]
### Expected behavior

in debug lever，when sample sent http request ,it should get value setted by PreProcessor

### Actual behavior

in info level、debug lever，result is not some，；

### Steps to reproduce the problem

1、customize a function，for example，the function^s referenceKey is __GV;
2、in a sample^s HeaderManager use __GV as Header value，for example，token=${__GV(result)}，token is Header key，${__GV(result)} is Header value；
3、result is set in PreProcessor
then ，info level is ok ，debug lever is wrong。

i guess org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase#setHeaderManager go wrong, it should not print header value as blow：
log.debug("    " + lValue.getHeader(i).getName() + "=" + lValue.getHeader(i).getValue());
![1703148375050](https://github.com/apache/jmeter/assets/13306569/b0d2a91e-08fb-4d50-a439-3fca1cb7891c)

your JMeterThread#executeSamplePackage will invoke HTTPSamplerBase#setHeaderManager before PreProcessor，and some value is cahched 。

when print header value , FunctionProperty#getStringValue、CompoundVariable#execute is called, in this method , Function#execute may return null,then the StringBuilder#toString() will return "null" , it may not right?

![图片1](https://github.com/apache/jmeter/assets/13306569/60763491-491c-4ef2-91ce-38dc33baf9ce)

### JMeter Version

5.5

### Java Version

8

### OS Version

windows

**Comment by vlsi** [comment]
This has been fixed in 5.6+, as function caching was disabled in https://github.com/apache/jmeter/pull/5788
