### ISSUE TITLE
jmeter hangs when open a jmx with a Big JSON  request param

### ISSUE THREAD

**Issue by ibingdian** [apache/jmeter#6233]
### Expected behavior

open the file immedidately

### Actual behavior

open the file used 10 minute or longer

### Steps to reproduce the problem

[report_jmx.zip](https://github.com/apache/jmeter/files/14061322/report_jmx.zip)

in the jmx, i have a httpsample , and it`s request param is a big json ,about 600k, when load the file ,the jmeter hangs up.

how to solve the problem.

the jmx is in report_jmx.zip.
the jvm are as follow
![jmeter jvm ](https://github.com/apache/jmeter/assets/13306569/efcab43e-1b14-4bce-b212-bc8b901c81e7)

### JMeter Version

5.6.3

### Java Version

1.8

### OS Version

windows

**Comment by dengfan2018** [comment]
I have the same question。

**Comment by ibingdian** [comment]
in jmeter.properties, set jsyntaxtextarea.linewrap=false

**Comment by vlsi** [comment]
We might automatically disable line wrap in jmeter if the body contains long lines.

**Comment by gianhub16** [comment]
When a request with a long payload is sent (for example with a base64 file code), when I click on this request on the View Result Tree crashes and I am forced to terminate jmeter.

I've tried with this in jmeter.properties, set jsyntaxtextarea.linewrap=false
No changes

**Comment by yyahav** [comment]
> When a request with a long payload is sent (for example with a base64 file code), when I click on this request on the View Result Tree crashes and I am forced to terminate jmeter.
> 
> I've tried with this in jmeter.properties, set jsyntaxtextarea.linewrap=false No changes

@gianhub16 
These following settings are in the same `jmeter.properties` file and are specific for View Results Tree:

```
# UI gets unresponsive when response contains very long lines,
# So we break lines by adding artificial line breaks
# The break is introduced somewhere in between soft_wrap_line_size..max_line_size
# We try to break on word boundaries first
view.results.tree.max_line_size=110000
view.results.tree.soft_wrap_line_size=100000

# Even with the above setting the UI can be unresponsive on large contents in the text view,
# so we allow to switch to a simpler view mode, that is faster, but does not break lines.
# Can be switched off by setting it to -1
view.results.tree.simple_view_limit=10000
```
