### ISSUE TITLE
kg.apc.jmeter.vizualizers.CorrectedResultCollector

### ISSUE THREAD

**Issue by lijie123bes** [apache/jmeter#6259]
### Steps to reproduce the problem

I've been working on building a JMX file (JMeter) from Jenkins for many days now. Suddenly, I encountered an error that says 'CannotResolveClassException: kg.apc.jmeter.vizualizers.CorrectedResultCollector'

### JMeter Version

5.5

### Java Version

jdk 8

### OS Version

linux

**Comment by vlsi** [comment]
`kg.apc.jmeter` does not come with JMeter, so I assume you had an extra plugin in `lib/...`.
If you need test plans with plugins, consider re-adding the plugin back.
