### ISSUE TITLE
how to debug in gui 

### ISSUE THREAD

**Issue by ibingdian** [apache/jmeter#6260]
### Use case

i download the latest jmeter source，then how to debug the gui？ 

### JMeter Version

5.6.3

### Java Version

17

### OS Version

windows

**Comment by vlsi** [comment]
Install IntelliJ IDEA, and use run with debugger.
<img width="594" alt="runGui with debugger" src="https://github.com/apache/jmeter/assets/213894/cbc6c8ab-89b4-44b7-b4f2-088d8477ce34">
