### ISSUE TITLE
The method name is misspelled for org.apache.jmeter.JMeter#startUdpDdaemon ?

### ISSUE THREAD

**Issue by linvaux** [apache/jmeter#6325]
### Expected behavior

org.apache.jmeter.JMeter#startUdpDaemon

### Actual behavior

org.apache.jmeter.JMeter#startUdpDdaemon
The method name is misspelled？daemon or ddaemon？

### Steps to reproduce the problem

check source code in `org.apache.jmeter.JMeter#startUdpDaemon`

### JMeter Version

5.6.3

### Java Version

Oracle java version "17.0.5" 2022-10-18 LTS

### OS Version

macOs Sonoma 14.6

**Comment by linvaux** [comment]
@vlsi

**Comment by FSchumacher** [comment]
Yes, that is a typo and it seems to be a private method, so we could change it.

Would you like to submit a PR?

**Comment by lowgiant** [comment]
Hi @FSchumacher 
If I can't get in touch, can I go ahead and create a PR?

**Comment by lowgiant** [comment]
Hi @FSchumacher
If the author can't be reached, can I go ahead and create a PR?
