### ISSUE TITLE
Jmeter plugins site is not working

### ISSUE THREAD

**Issue by manimaran-madhappan** [apache/jmeter#6327]
### Expected behavior

I am trying to run my CI pipeline as usual, but it was failing to install JMeter plugins

### Actual behavior

The commandrunner and plugin manager jars will automatically install the required jars.

### Steps to reproduce the problem

https://[jmeter-plugins.org](https://jmeter-plugins.org/)/ site is not working, which is the source reason for the failures I believe

### JMeter Version

5.6.3

### Java Version

openjdk 17

### OS Version

windows, ubuntu

**Comment by linvaux** [comment]
acess https://maxcdn.bootstrapcdn.com timeout ， so web site could not load successfully

**Comment by FSchumacher** [comment]
jmeter-plugins is not managed by the JMeter project. For help about jmeter-plugins go to [their forum](https://groups.google.com/g/jmeter-plugins)
