### ISSUE TITLE
Why jmeter mix write by Java and kotlin

### ISSUE THREAD

**Issue by linvaux** [apache/jmeter#6349]
hi, I have been reading the JMeter source code recently and noticed that the 5.6.3 version uses Java and Kotlin to mix write code. What was the reason for considering this?

**Comment by FSchumacher** [comment]
You could look at the dev list archive, for example https://lists.apache.org/thread/6vzc4pnsbng542ohspg58s4rmgv5t56x

**Comment by linvaux** [comment]
ok, thanks
