### ISSUE TITLE
Dot Net 8.0 Website -- how to generate jmx Script.

### ISSUE THREAD

**Issue by Shikku096** [apache/jmeter#6351]
I wanted  to load  test a website developed in  Dot Net 8.0, can you help  me  how to generate JM X scripts for entire website  

i generated with blaze meter it is not capturing the sessions/cookies  of the websites

**Comment by milamberspace** [comment]
Github issues is not a help forum, please use mailing list.
https://jmeter.apache.org/mail2.html

**Comment by vdaburon** [comment]
Yes but where is the help forum ? No more on google group.
