### ISSUE TITLE
Артефакты на графическом интерфейсе Jmeter

### ISSUE THREAD

**Issue by KuzminMax** [apache/jmeter#6360]
### Actual behavior

![Скриншот 08-10-2024 141637](https://github.com/user-attachments/assets/0d100740-5ca1-441e-bfa0-f1940ff69fa3)

правктически сразу после запуска JMeter, начинает плыть 

### Steps to reproduce the problem

правктически сразу после запуска JMeter, начинает плыть 
![Скриншот 08-10-2024 141637](https://github.com/user-attachments/assets/72e9de0f-5495-4733-9bfe-a3905db9ca1f)

### JMeter Version

5.6.3

### Java Version

23

### OS Version

Windows 10

**Comment by FSchumacher** [comment]
Looks like #5737 

Try to set the JVM flag `-Dsun.java2d.d3d=false`

**Comment by KuzminMax** [comment]
> Похоже на #5737
> 
> Попробуйте установить флаг JVM`-Dsun.java2d.d3d=false`

как это сделать?

"-Dsun.java2d.d3d" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

**Comment by FSchumacher** [comment]
You could add the JVM parameter to `JVM_ARGS` as noted in https://github.com/apache/jmeter/issues/5737#issuecomment-1662353684 and the comment below that.

**Comment by FSchumacher** [comment]
Closing, as it is very probably the issue #5737 and no further interaction from OP. Feel free to re-open this, if you think this is another issue and have more information.
