### ISSUE TITLE
I want to give jmeter a quick luanch way in windows 11 platform

### ISSUE THREAD

**Issue by q2333gh** [apache/jmeter#6365]
### Use case

Common case is like this: 
When user type `win+s` then input `jmeter` so they can quick luanch it.

Since if we create a shortcut of `jmeter.bat` into  `C:\Users\<username>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs`  
its not gonna work for quick luanch search . might due to `.bat` suffix.

So i write this code:
And it works:
```py
import subprocess
subprocess.call([r"C:\<your-location>\apache-jmeter-5.6.3\bin\jmeter.bat"])
#### build a distribution file:
# pyinstaller --onefile .\jmeter.py
```
so this python code generate a binary excutable .exe  suffix file  to us. we put its shorcut in to `Programs` folder.
It then will work for quick luanch.

Guys do you think i might should create a PR base on this ? 

### JMeter Version

5.6

**Comment by linvaux** [comment]
no necessary

**Comment by FSchumacher** [comment]
I don't think, that adding a Python dependency is a good way to mitigate this problem, if it is a problem at all.

**Comment by q2333gh** [comment]
OK, i agreed with you guys.
