### ISSUE TITLE
Build and test for Linux/ARM64 

### ISSUE THREAD

**Issue by odidev** [apache/jmeter#6367]
### The documentation URL

https://jmeter.apache.org/index.html

## Description  

For aarch64 platform, I have built `Jmeter` from source.  

## Steps   

Following [steps](https://github.com/apache/jmeter/commit/cecd1b9254c1fb0101bdca20ca571d6654d42ca8) were used for the building and installation:  

``` 
# sudo apt update 
# sudo apt install make cmake wget openjdk-11-jdk ant -y 
# wget https://github.com/apache/jmeter/archive/refs/tags/v5_0.tar.gz 
# tar -xvf  v5_0.tar.gz 
# cd jmeter-5_0 
# ant download_jars 
# ant 
```  
## Outcome  

To validate that the build was successful we ran a version check. The version info returned matched the expected value.  

  

All this information is also added to [Software Ecosystem Dashboard for Arm](https://www.arm.com/developer-hub/ecosystem-dashboard/).

**Comment by FSchumacher** [comment]
I am not really sure, what this *issue* is about? JMeter is a Java program, which should run everywhere, where you have a JRE available. Apart from that, the version 5.0 is really, really old.
